### ISSUE TITLE
Error "No suitable transform was found to encode or decode"

### ISSUE THREAD

**Issue by jbsterasawas** [microsoft/Windows-universal-samples#1295]
**Which sample are you reporting a bug in?**

Manual_camera_controles_sample (C#)

**Describe the bug**
The error occurs around StartPreviewAsync().
The following is error mesage.

> System.Runtime.InteropServices.COMException
  HResult=0xC00D5212
  Message=No suitable transform was found to encode or decode.
No suitable transform was found to encode or decode.
  Source=System.Private.CoreLib
  Stack Trace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CameraManualControls.MainPage.<StartPreviewAsync>d__62.MoveNext() in C:\test\Manual_camera_controls_sample\cs\MainPage.xaml.cs:line 374
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CameraManualControls.MainPage.<InitializeCameraAsync>d__61.MoveNext() in C:\test\Manual_camera_controls_sample\cs\MainPage.xaml.cs:line 349
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at CameraManualControls.MainPage.<OnNavigatedTo>d__49.MoveNext() in C:\test\Manual_camera_controls_sample\cs\MainPage.xaml.cs:line 130
  This exception was originally thrown at this call stack: 
    [External Code]
    CameraManualControls.MainPage.StartPreviewAsync() (in MainPage.xaml.cs)
    [External Code]
    CameraManualControls.MainPage.InitializeCameraAsync() (in MainPage.xaml.cs)
    [External Code]
    CameraManualControls.MainPage.OnNavigatedTo(Windows.UI.Xaml.Navigation.NavigationEventArgs) (in MainPage.xaml.cs)

**To Reproduce**
1. Debug with Visual Studio

**Expected behavior**
Preview of camera is shown.

**Configuration**

* Language/architecture/flavor:  C#/WinRT x64 Debug
* Windows platform and build number: Windows 10 environment is "Windows 10 version Dev (OS Build 21376.1)"

* Visual Studio version:  16.9.4

**Additional context**
When I debuged, I accepted "camera access" and "microphone access" when running the sample code, and the Package.appxmanifest file includes following capabilities.
> <Capabilities>
    <uap:Capability Name="picturesLibrary" />
    <DeviceCapability Name="webcam" />
    <DeviceCapability Name="microphone" />
  </Capabilities>

**Comment by oldnewthing** [comment]
(Note: Sample is CameraManualControls.) It sounds like your camera produces a frame format that the MediaCapture doesn't support. What format is it?
