### ISSUE TITLE
Wi-Fi Direct sample pairing issues for android devices

### ISSUE THREAD

**Issue by Larry-Luo-A** [microsoft/Windows-universal-samples#1354]
**Which sample are you reporting a bug in?**
[WiFiDirect](https://github.com/microsoft/Windows-universal-samples/tree/main/Samples/WiFiDirect)

**Describe the bug**
Hi, 
I use the WiFiDirect sample with secnario Advertiser to pair with an Android device (OPPO Reno6) , the first connection is ok, but I always encounter problems after the second connection, Below is the Exception:

Exception in FromIdAsync:System.Exception: Element not found. (Exception from HRESULT: 0x80070490)
    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
    at SDKTemplate.Scenario1_Advertiser.<HandleConnectionRequestAsync>d__12.MoveNext()
  
It happens  on wfdDevice = await WiFiDirectDevice.FromIdAsync(connectionRequest.DeviceInformation.Id); 
I've investigated the content of connectionRequest and it's not much different when windows is connected as a Connector. 

Any suggestions or clarifications for situations like this? Thanks

**To Reproduce**
1. Run Windows WiFiDirect sample
2. Click "Start Advertisement" button for listen
3. Android device scan Wi-Fi Direct device and find my laptop
4. Click laptop name from android device to do connecting
5. Show the pair message alert on windows device and click "yes"
6. Successfully connected both devices
7. Disconnect from either side
8. Android device scans and reconnects
9. Connecting fail and exception show : Element not found. (Exception from HRESULT: 0x80070490)

**Expected behavior**
The connection after the second time should also be successfully paired

**Configuration**
Add "Push Button" Config Method

**Comment by MurrayCapricorns** [comment]
Actually, The Windows Wifi-Direct function is so hard to use. For this issue, the solution should be just waiting 2 minutes which will be ok.

**Comment by MurrayCapricorns** [comment]
So,I wanna say as you saw while still not having anyone replyed...

**Comment by oldnewthing** [comment]
I've asked the feature team to investigate.

**Comment by wangf1978** [comment]
Hitting the same issue.

**Comment by fiasko131** [comment]
Same here.
@iKunCai How to restart Microsoft-Wifi-Direct-virtual-adapters ?
