### ISSUE TITLE
Try to search an item in XamlPivot

### ISSUE THREAD

**Issue by Afanyiyu** [Microsoft/Windows-universal-samples#571]
XamlPivot.Scenario2
Try to search an item and use the suggestion. 
The app will exit.

**Comment by oldnewthing** [comment]
You have to click the suggestion from the dropdown, not by 

````
System.Runtime.InteropServices.COMException occurred
  HResult=0x80000019
  Message=An async operation was not properly started.

Only a single ContentDialog can be open at any time.
  Source=
  StackTrace:
   at Windows.UI.Xaml.Controls.ContentDialog.ShowAsync()
   at PivotCS.Scenario2.<>c__DisplayClass12_0.<<ShowItem>b__0>d.MoveNext() in S:\repos\rs3\Samples\XamlPivot\cs\Scenario2.xaml.cs:line 118
````

Re-entrancy bug in `ShowItem`.

**Comment by oldnewthing** [comment]
Okay, I fixed the problem. Will be in the next update.
