### ISSUE TITLE
ListView and GridView sample, binding error

### ISSUE THREAD

**Issue by Swifter** [Microsoft/Windows-universal-samples#709]
When the project is changed from Arm to x64 so it will run on the desktop, recompiled and run, a binding error occurs, to wit:  

System.InvalidCastException occurred
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Char' to type 'System.String'.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at ListViewSample.SimpleListViewSample.SimpleListViewSample_obj10_Bindings.Update_Key(Object obj, Int32 phase) in C:\dev\Windows-universal-samples-master\Windows-universal-samples-master\Samples\XamlListView\cs\obj\x64\Debug\Samples\SimpleListViewSample\SimpleListViewSample.g.cs:line 318
   at ListViewSample.SimpleListViewSample.SimpleListViewSample_obj10_Bindings.Update_(GroupInfoList obj, Int32 phase) in C:\dev\Windows-universal-samples-master\Windows-universal-samples-master\Samples\XamlListView\cs\obj\x64\Debug\Samples\SimpleListViewSample\SimpleListViewSample.g.cs:line 307
   at ListViewSample.SimpleListViewSample.SimpleListViewSample_obj10_Bindings.Update() in C:\dev\Windows-universal-samples-master\Windows-universal-samples-master\Samples\XamlListView\cs\obj\x64\Debug\Samples\SimpleListViewSample\SimpleListViewSample.g.cs:line 277
   at ListViewSample.SimpleListViewSample.SimpleListViewSample_obj10_Bindings.DataContextChangedHandler(FrameworkElement sender, DataContextChangedEventArgs args) in C:\dev\Windows-universal-samples-master\Windows-universal-samples-master\Samples\XamlListView\cs\obj\x64\Debug\Samples\SimpleListViewSample\SimpleListViewSample.g.cs:line 230

This happens because the Key is of type Char and the TextBox cannot bind this.  The fix is in Contacts.cs, at line 116, simply change the g.GroupName type to string as you store it in info.Key

             //   info.Key = g.GroupName; 
                   info.Key = g.GroupName.ToString();

**Comment by oldnewthing** [comment]
Thanks for the diagnosis. Will fold this fix into the update v5.0.4.
