### ISSUE TITLE
Geolocator throws PipeCloseException when calling GetGeopositionAsync method in windows 10 app

### ISSUE THREAD

**Issue by rohitkumar07** [Microsoft/Windows-universal-samples#79]
Here is the stack trace:
System.Exception: The pipe is being closed. (Exception from HRESULT: 0x800700E8)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at GeolocationCS.Scenario2.<GetGeolocationButtonClicked>d__6.MoveNext()

**Comment by roaasakr** [comment]
Hi Rohit,

Can you mention the steps to repro that error? Which platform did you use? 
 
-Roaa

**Comment by AdamBraden** [comment]
Closing as there has not been a response in 7 days.  In that time all samples have gotten a refresh.  Open a new issue if there is a problem.
