### ISSUE TITLE
MapControl Scenario8 crashes on Initialize

### ISSUE THREAD

**Issue by pierresa** [Microsoft/Windows-universal-samples#823]
January samples downloaded; start MapControl and try scenario 8, 

System.Runtime.InteropServices.SEHException
  HResult=0x80004005
  Message=External component has thrown an exception.
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

**Comment by pierresa** [comment]
also scenario2 Add 3D element crash with similar code:
System.Runtime.InteropServices.COMException
  HResult=0x80004005
  Message=Unspecified error

Failed to create MapModel3D from 3MF stream.
  Source=Windows
  StackTrace:
   at Windows.Foundation.IAsyncOperation`1.GetResults()
   at System.Threading.Tasks.AsyncInfoToTaskBridge`2.Complete(IAsyncInfo asyncInfo, Func`2 getResultsFunction, AsyncStatus asyncStatus)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SDKTemplate.Scenario2.<mapElement3DAddButton_Click>d__8.MoveNext() in C:\Users\Pierre\Downloads\January Windows-universal-samples-master\Windows-universal-samples-master\Samples\MapControl\cs\Scenario2.xaml.cs:line 86

**Comment by pierresa** [comment]
Same thing with February samples scenario 8 crashes

**Comment by pierresa** [comment]
This seems to be linked with last Windows 10 fast ring updates. The problem does not exist on 1709
